[project]
name = "whagodri-alt"
version = "1.0.0"
description = "Allows WhatsApp users on Android to extract their backed up WhatsApp data from Google Drive"
channels = ["conda-forge"]
platforms = ["win-64"]
license = "GPL-3.0-or-later"
repository = "https://github.com/notPlancha/whagodri-alt"

[tasks]
main = "python ./WhatsAppGDExtract.py sync"

[dependencies]
python = ">=3.12.4,<3.13"
urllib3 = "<2.0"

[pypi-dependencies]
gpsoauth = "==1.1.1"
